# Generated by Django 5.2.5 on 2025-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='آیکون دسته\u200cبندی با فرمت SVG یا PNG', upload_to='categories/icons/', verbose_name='آیکون'),
        ),
    ]
