# Generated by Django 5.2.5 on 2025-08-11 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Enter a valid "slug" with letters, numbers, underscores or hyphens.', regex='^[-\\w]+$')]),
        ),
    ]
